# Generated by Django 4.1.4 on 2022-12-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_iscompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='total_money_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='appuser',
            name='total_money_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
