# Generated by Django 4.1.4 on 2022-12-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlo_store', '0002_item_category_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
