# Generated by Django 4.1.4 on 2022-12-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlo_store', '0003_item_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets', models.DecimalField(decimal_places=2, max_digits=9)),
                ('liabilities', models.DecimalField(decimal_places=2, max_digits=9)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
