# Generated by Django 4.1.4 on 2022-12-17 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlo_store', '0006_itemrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcomment',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mlo_store.item'),
        ),
        migrations.AlterField(
            model_name='itemcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemrating',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlo_store.item'),
        ),
        migrations.AlterField(
            model_name='itemrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
